---
# Tasks file for RMQ
    - name: Install Erlang package
      yum: name=https://github.com/rabbitmq/erlang-rpm/releases/download/v20.1.7/erlang-20.1.7-1.el6.x86_64.rpm state=present

    - name: Install Socat package
      yum: name=socat state=present

    - name: Install rabbitmq-server (v3.6.12)
      yum: name=http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.12/rabbitmq-server-3.6.12-1.el6.noarch.rpm state=present

    - name: Enable rabbitmq-server to survive reboot
      service: name=rabbitmq-server enabled=yes

    - name: Rabbitmq config
      template: src=rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config

    - name: Set erlang cookie
      template: src=erlang.cookie dest=/var/lib/rabbitmq/.erlang.cookie owner=rabbitmq group=rabbitmq mode=0400

    - name: Enable plugins
      rabbitmq_plugin: names=rabbitmq_management,rabbitmq_federation state=enabled prefix=/usr/lib/rabbitmq/

    - name: Start RMQ Server
      action: service name=rabbitmq-server state=restarted


    - name: Adding hosts entry of master
      lineinfile: dest=/etc/hosts line="{{ hostvars[item]['ansible_all_ipv4_addresses'][0] }}   {{ hostvars[item]['ansible_hostname'] }}"
      with_items:  "{{ rabbitmq_master }}"
      when: cluster

    - name: Adding hosts entry of slaves
      lineinfile: dest=/etc/hosts line="{{ hostvars[item]['ansible_all_ipv4_addresses'][0] }}   {{ hostvars[item]['ansible_hostname'] }}"
      with_items: "{{ rabbitmq_slave }}"
      when: cluster


    - name: Getting RMQ master hostname
      set_fact:
       rmq_hostname: "{{ hostvars[item]['ansible_hostname'] }}"
      with_items: "{{ rabbitmq_master }}"
      when: cluster

    - name: Joining cluster
      shell: |
        rabbitmq-server -detached
        rabbitmqctl stop_app
        rabbitmqctl join_cluster rabbit@{{ rmq_hostname }}
        rabbitmqctl start_app
      when: inventory_hostname != rabbitmq_master and cluster


    - name: Manage Rabbitmq vhost and user on master
      shell: |
        rabbitmqctl add_vhost {{ item.vhost }}
        rabbitmqctl add_user {{ item.user }} {{ item.password }}
        rabbitmqctl set_user_tags {{ item.user }} {{ tag }}
        rabbitmqctl set_permissions -p {{ item.vhost }} {{ item.user }} ".*" ".*" ".*"
      when: inventory_hostname == rabbitmq_master

      with_items: "{{ modules }}"

    - name: Set default policy for HA to all queues/exchanges
      rabbitmq_policy: vhost={{ item.vhost }} name=HA-{{ item.user }} pattern='.*' tags="ha-mode=all" priority=0
      with_items: "{{ modules }}"
      when: inventory_hostname == rabbitmq_master and cluster
